### ISSUE TITLE
Feature Request: Additional Animation Parameters for Shine ChangeEffect

### ISSUE THREAD

**Issue by mergesort** [movingparts-io/Pow#10]
I hope this is the right place to ask for more fine tuning, but either way thank you very much for the library!

I was trying to use the `.shine` ChangeEffect for animating a button tap, but the animation duration is too long for my use case. I see that other ChangeEffect's have parameters to try and fine tune the animation, and was hoping that it would be possible to add additional parameters to `.shine`. While I only want the timing to be faster, I could see the edges being exposed as a parameter being useful to others as well, but I'll leave that to your best discretion.

Happy to provide any more information that may be useful, and thank you again!

**Comment by robb** [comment]
Hi @mergesort,

thanks for reaching out – I think that's a reasonable request, we'll look into it and will report back shortly.

**Comment by mergesort** [comment]
Thanks a lot! In that case I'd like to expand the request a tiny bit to ask for more generally any `ChangeEffect` or `Transition` that has tunable parameters to expose those. No rush of course, have a great weekend. 🙂
