### ISSUE TITLE
Proposal: A Slightly Less Imperative .feedbackHapticSelection Option

### ISSUE THREAD

**Issue by mergesort** [movingparts-io/Pow#16]
One of the most common times I find myself using a selection haptic is when I want to provide a user feedback upon tapping a button. I've been able to integrate Pow's new `.changeEffect(.feedbackHapticSelection, value: someValue)` really effectively in picker-type controls, but unfortunately a button tap an imperative action, which does not work great out the box with SwiftUI's and Pow's declarative APIs.

A workaround I came up with is to hold my own state, in a way that isn't particularly pretty (and seems to create some sort of extra tap once in a while for some reason I can't track down in my code.)

 What I'm doing is

1. Creating a `View` that holds a `Button`.
2. Attach the `changeEffect`, based on some internal state keeping track of whether the haptic feedback is active.
3. When the user taps the button, call `activateSelectionHaptic` to set the haptic active, and set it inactive 0.5 seconds later.

```swift
@State private var isActive = false

var body: some View {
    Button("Selection Demo", action: {
        print("Selected!")

        Task { await self.activateSelectionHaptic(isActive: $isActive) }
    })
    .changeEffect(.feedbackHapticSelection, value: isActive == true, isEnabled: self.preferences.hasHapticsEnabled)
}
```

```swift
extension View {

    func activateSelectionHaptic(isActive: Binding<Bool>) async {
        isActive.wrappedValue = true
        do {
            try await Task.sleep(for: .seconds(0.5))
            isActive.wrappedValue = false
        } catch {
            isActive.wrappedValue = false
        }
    }

}
```

This isn't pretty but it does wrap up some logic that I found myself rewriting often. I was wondering if you had any ideas for how I could make this better, or perhaps with first party access include a more semantically viable version built into Pow?

Thank you as always!

**Comment by robb** [comment]
Oh, and the `self.preferences.hasHapticsEnabled` shouldn't be needed as the change effect should be fire and forget (lmk if it's not).

**Comment by mergesort** [comment]
I like the buttonStyle idea, that's something I hadn't considered but fits really nicely. I think I may be holding the selection feedback generator wrong though because I'm not getting the same effect. This is the `ButtonStyle` I created.
```swift
struct HapticFeedbackStyle: ButtonStyle {

    var isEnabled = false

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .changeEffect(.feedbackHapticSelection, value: configuration.isPressed == true, isEnabled: isEnabled)
    }

}
```

The call-site looks like this.
```swift
Button(action: {
    debugButtonAction()
}, label: {
    Image.icons.debugCircleFilled
        .foregroundColor(palette.alternativeBackground)
})
.buttonStyle(HapticFeedbackStyle(isEnabled: self.preferences.hasHapticsEnabled))
```

Side note: `self.preferences.hasHapticsEnabled` is actually a condition in my app because the user can disable haptics entirely, so we can actually ignore that.

---

When I tap the button, it feels different than if you'd called `selectionGenerator.selectionChanged()` in the `Button(action: {})` block. Rather than a small tap it feels like a bit of a rumble, if I had to guess it's the `selectionChanged()` effect being fired back to back.

I wouldn't be surprised if I was holding it wrong, but since I don't have source code access figured I'd ask here to see if this isn't how you intended it to be used.

**Comment by robb** [comment]
Yeah, I think the different feel is `isPressed` changing twice, once when you tap and once when you let go.

Here's how I would write this using a PrimitiveButtonStyle:

```swift
import Pow
import SwiftUI

struct ContentView: View {
    @State
    var feedbackEnabled = true

    var body: some View {
        VStack {
            GroupBox {
                Toggle("Feedback", isOn: $feedbackEnabled)
            }

            Spacer()

            Button("Do Something") {
                print("done something")
            }

            Button("Do Something else") {
                print("done something else")
            }

            Spacer()
        }
        .environment(\.hapticFeedbackEnabledKey, feedbackEnabled)
        .buttonStyle(.feedback)
        .padding()
    }
}

struct FeedbackButtonStyle: PrimitiveButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        FeedbackButton(configuration: configuration)
    }
}

extension PrimitiveButtonStyle where Self == FeedbackButtonStyle {
    static var feedback: Self { FeedbackButtonStyle() }
}

// A separate view is required to get access to the environment.
private struct FeedbackButton: View {
    @Environment(\.hapticFeedbackEnabledKey)
    var hapticFeedbackEnabledKey

    @State
    // Alternatively, use a change tracking struct here.
    var interactionCount: Int = 0

    var configuration: PrimitiveButtonStyleConfiguration

    var body: some View {
        Button(role: configuration.role) {
            interactionCount += 1

            configuration.trigger()
        } label: {
            configuration.label
        }
        // You could style this yourself here, hardcode your preferred button
        // style or parameterize the view by it.
        .buttonStyle(.borderedProminent)
        .changeEffect(.feedbackHapticSelection, value: interactionCount, isEnabled: hapticFeedbackEnabledKey)
    }
}

extension EnvironmentValues {
    struct HapticFeedbackEnabledKey: EnvironmentKey {
        static var defaultValue: Bool = true
    }

    var hapticFeedbackEnabledKey: Bool {
        get { self[HapticFeedbackEnabledKey.self] }
        set { self[HapticFeedbackEnabledKey.self] = newValue }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

**Comment by robb** [comment]
Hope this was improved by 0.2.0 – feel free to reopen if it's not :)
