### ISSUE TITLE
Using Pow with CocoaPods.

### ISSUE THREAD

**Issue by gtokman** [movingparts-io/Pow#26]
I'm trying to integrate Pow as a vendor framework in a component library we maintain in a private CocoaPod.

I downloaded the XCFramework from `https://packages.movingparts.io/binaries/pow/0.2.1/Pow.xcframework.zip` and am referencing it in the `.podspec` locally:

```
...
s.ios.vendored_frameworks = "ios/VendorFrameworks/Pow.xcframework"
...
```

Everything seems to be compiling fine but when I use it in our mobile client I see an **error**:
```
Generating Pods project
[!] Unable to install vendored xcframework `Pow` for Pod `CandleUI`, because it contains both static and dynamic frameworks.
error Command failed with exit code 1.
```

Do you think this could be because it includes dylibs like SwiftUI or is released as a dylib? I'm a little bit out of my depth here and would appreciate any suggestions you may have.

**Comment by gtokman** [comment]
Fixed it by editing the `info.plist` and removing the mac-os/catalyst frameworks.

**Comment by robb** [comment]
Good to know, thanks! <3
