### ISSUE TITLE
Missing Simulator Slice? 

### ISSUE THREAD

**Issue by robb** [movingparts-io/Pow#9]
> Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/jdavis/Development/Games/LNGames/Pow.framework/Pow' for architecture arm64

I've tried adding the .xcframework and while the project builds and runs fine on device, Xcode previews gives me the above errors. :(

_Originally posted by @ismyhc in https://github.com/movingparts-io/Pow/issues/6#issuecomment-1279077888_

**Comment by robb** [comment]
@ismyhc Thanks for filing the issue, I haven't seen this myself and am investigating now.

Can you confirm you've dragged the entire xcframework into your project and are linking against that (instead of the individual .frameworks contained within)?

It should look a little something like this:

<img width="311" src="https://user-images.githubusercontent.com/212465/195991528-69afbb92-baa5-4fa4-b9a6-db61bd808991.png">

<img width="274" src="https://user-images.githubusercontent.com/212465/195991527-50c4e243-12cd-4562-89f3-13a5c782d6ea.png">

Are you running on an Intel Mac? What versions of Xcode and macOS are you using?

**Comment by ismyhc** [comment]
@robb Here's what it looks like in Xcode & in the actual folder in finder. Its weird I don't get a folder like you have in Xcode. 

![Screen Shot 2022-10-15 at 11 14 03 AM](https://user-images.githubusercontent.com/840551/195994003-f799d296-5a26-4ff9-994c-a0d4908b2a04.png)

**Comment by robb** [comment]
Ok, that looks right. Are you on an Intel-based Mac?

**Comment by ismyhc** [comment]
> Ok, that looks right. Are you on an Intel-based Mac?

Sorry, no im on apple silicon.
![Screen Shot 2022-10-15 at 11 18 35 AM](https://user-images.githubusercontent.com/840551/195994218-bedd3abe-e1be-418f-9cea-e08bc92b056b.png)

**Comment by ismyhc** [comment]
@robb Actually now its working. I removed everything. Restarted Xcode and it works! :)

**Comment by robb** [comment]
lol – Xcode do be like that. Glad to hear it sorted itself out!

**Comment by ismyhc** [comment]
> lol – Xcode do be like that. Glad to hear it sorted itself out!

I wonder if maybe after removing it from SPM, I needed to restart Xcode before adding it as xcframework? At any rate, thanks for you quick response! License purchase on its way :)

**Comment by robb** [comment]
Xcode works in mysterious ways! Quick heads up, I'll remove your issue in the other thread to keep that one on topic. Feel free to file new issues if you run into any roadblocks.
